#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-validation-api
Version  : 1.1.0.final
Release  : 1
URL      : https://repo1.maven.org/maven2/javax/validation/validation-api/1.1.0.Final/validation-api-1.1.0.Final.jar
Source0  : https://repo1.maven.org/maven2/javax/validation/validation-api/1.1.0.Final/validation-api-1.1.0.Final.jar
Source1  : https://repo1.maven.org/maven2/javax/validation/validation-api/1.1.0.Final/validation-api-1.1.0.Final.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-validation-api-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-validation-api package.
Group: Data

%description data
data components for the mvn-validation-api package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/javax/validation/validation-api/1.1.0.Final
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/javax/validation/validation-api/1.1.0.Final

mkdir -p %{buildroot}/usr/share/java/.m2/repository/javax/validation/validation-api/1.1.0.Final
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/javax/validation/validation-api/1.1.0.Final


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/javax/validation/validation-api/1.1.0.Final/validation-api-1.1.0.Final.jar
/usr/share/java/.m2/repository/javax/validation/validation-api/1.1.0.Final/validation-api-1.1.0.Final.pom
